

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entidades
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MyContext : DbContext
{
    public MyContext()
        : base("name=MyContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Calificaciones> Calificaciones { get; set; }

    public DbSet<Carteleras> Carteleras { get; set; }

    public DbSet<Generos> Generos { get; set; }

    public DbSet<Peliculas> Peliculas { get; set; }

    public DbSet<Reservas> Reservas { get; set; }

    public DbSet<Sedes> Sedes { get; set; }

    public DbSet<TiposDocumentos> TiposDocumentos { get; set; }

    public DbSet<Usuarios> Usuarios { get; set; }

    public DbSet<Versiones> Versiones { get; set; }

}

}

